"""add ingredient_aliases table

Revision ID: 4212f0c676ef
Revises: 0002
Create Date: 2026-03-31 18:59:30.360000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4212f0c676ef'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_aliases')
    # ### end Alembic commands ###
