"""add ingredient_aliases table

Revision ID: 4212f0c676ef
Revises: 0002
Create Date: 2026-03-31 18:59:30.360000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4212f0c676ef'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.drop_index(op.f('ix_analysis_feedback_food_id'), table_name='analysis_feedback')
    op.drop_index(op.f('ix_analysis_feedback_task_id'), table_name='analysis_feedback')
    op.drop_index(op.f('ix_ingredient_analyses_ingredient_id'), table_name='ingredient_analyses')
    op.drop_index(op.f('ix_ingredient_analyses_is_active'), table_name='ingredient_analyses')
    op.drop_index(op.f('ix_product_analyses_food_id'), table_name='product_analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_analyses_food_id'), 'product_analyses', ['food_id'], unique=False)
    op.create_index(op.f('ix_ingredient_analyses_is_active'), 'ingredient_analyses', ['is_active'], unique=False)
    op.create_index(op.f('ix_ingredient_analyses_ingredient_id'), 'ingredient_analyses', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_analysis_feedback_task_id'), 'analysis_feedback', ['task_id'], unique=False)
    op.create_index(op.f('ix_analysis_feedback_food_id'), 'analysis_feedback', ['food_id'], unique=False)
    op.drop_table('ingredient_aliases')
    # ### end Alembic commands ###
