packages:
  - apps/*
  - tooling/*

catalog:
  "@eslint/js": ^9.38.0
  "@types/node": ^22.18.12
  "@vitejs/plugin-react": 5.1.0
  "@tailwindcss/vite": ^4.1.16
  eslint: ^9.38.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12
  vite: 7.1.12

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.2
    react-dom: 19.1.2

  react18:
    "@types/react": ~18.0.0
    "@types/react-dom": ~18.0.0
    react: 18.0.0
    react-dom: 18.0.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  vite: 7.1.12

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
